# name: Fazer deploy vps

# on:
#   push:
#     branches:
#       - main

# env:
#   PASTA_APLICACAO: /mnt/aplicacoes/deploy
#   VPS_USUARIO: ${{ secrets.VPS_USUARIO }}
#   VPS_IP: ${{ secrets.VPS_IP }}
#   VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Configurar ssh
#         uses: kielabokkie/ssh-key-and-known-hosts-action@v1
#         with:
#           ssh-private-key: ${{ env.VPS_SSH_KEY }}
#           ssh-host: ${{ env.VPS_IP }}
          
#       - name: Copiar arquivo
#         run: scp -oStrictHostKeyChecking=no -r $(pwd)/* ${{ env.VPS_USUARIO }}@${{ env.VPS_IP }}:${{ env.PASTA_APLICACAO }}

#       - name: Executar build docker
#         run: ssh ${{ env.VPS_USUARIO }}@${{ env.VPS_IP }} 'sudo docker compose -f ${{ env.PASTA_APLICACAO }}/docker/docker-compose.yml up --build -d --force-recreate'